services:
  mudmaker:
    build:
      context: .
      dockerfile: Dockerfile
    image: mudmaker:latest
    depends_on:
      - mudzipserver
    ports:
      - "127.0.0.1:8081:8081"
    restart: unless-stopped

  mudzipserver:
    build:
      context: .
      dockerfile: Dockerfile
      target: mudzipserver
    image: mudmaker-mudzipserver:latest
    restart: unless-stopped
